# Generated by Django 4.0.6 on 2022-08-01 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_current_bid_bid_amount_bid_is_awarded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='is_awarded',
        ),
        migrations.AddField(
            model_name='lot',
            name='awarded_bid',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.bid'),
        ),
    ]
