# Generated by Django 4.1 on 2022-08-03 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_bid_is_awarded_lot_awarded_bid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
